<a href="https://colab.research.google.com/github/rukaachan/Data-Science-BISAAI-PML/blob/main/DS_BISAAI_PML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dasar Pemrograman Python

In [ ]:
print("Hello World")

Hello World


### Statement & Variabel

In [ ]:
nama = "bintang"
nilai = 10
tempat = "kebun binatang"
print("Nama: " +nama, "Nilai: " +str(nilai), "Tempat: " +tempat)

Nama: bintang Nilai: 10 Tempat: kebun binatang


### Operator

In [ ]:
a = 5
b = 5
hasil = a + b
print("Jumlah: " +str(hasil))

Jumlah: 10


### Operator Perbandingan

In [ ]:
a = 3
b = 5
hasil = (a > b)
print(hasil)

False


### Operator Sleksi

In [ ]:
a = 3
b = 5

# Perbandingan antara a dan b
if a > b:
    print(f"{a} lebih besar daripada {b}")
elif a < b:
    print(f"{a} lebih kecil daripada {b}")
else:
    print(f"{a} sama dengan {b}")


3 lebih kecil daripada 5


## Matematika dan Statistika

In [2]:
import numpy as np

### Scalar, Vector, Matrix

### Scalar

In [ ]:
s = 8
print(s)

8


### Vector

In [ ]:
v = np.array([[1,2,3,4,5,6,7,8,9]])
print(v.shape)
print(v)

(1, 9)
[[1 2 3 4 5 6 7 8 9]]


### Matrix

In [ ]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m.shape)
print(m)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Operasi Dasar pada Matrix dan Vector

#### Penjumlahan dan Pengurangan pada Matrix dan Vector

In [ ]:
v1 = np.array([[2,7,9]])
v2 = np.array([[5,7,3]])
penjumlahan_vector = v1+v2
pengurangan_vector = v1-v2

print(penjumlahan_vector)
print(pengurangan_vector)

[[ 7 14 12]]
[[-3  0  6]]


In [ ]:
m1 = np.array([[2,7,9], [5,8,1]])
m2 = np.array([[4,1,6], [5,7,3]])
penjumlahan_matrix = m1+m2
pengurangan_matrix = m1-m2

print(penjumlahan_matrix)
print(pengurangan_matrix)

[[ 6  8 15]
 [10 15  4]]
[[-2  6  3]
 [ 0  1 -2]]


#### Transpose pada Matrix dan Vector

In [ ]:
# cara pertama dalam vector
v1 = np.array([[2,7,9]])
v1_transpose = np.transpose(v1)

print(v1_transpose)

[[2]
 [7]
 [9]]


In [ ]:
# cara kedua dalam vector
v1_transpose = v1.transpose()

print(v1_transpose)

[[2]
 [7]
 [9]]


In [ ]:
# cara pertama dalam matrix
m1 = np.array([[2,7,9], [5,8,1]])
m1_transpose = np.transpose(m1)

print(m1_transpose)

[[2 5]
 [7 8]
 [9 1]]


In [ ]:
# cara kedua dalam matrix
m1_transpose = m1.transpose()

print(m1_transpose)

[[2 5]
 [7 8]
 [9 1]]


#### Perkalian pada Matrix dan Vector

In [ ]:
v1 = np.array([[2,7,9]])
v2 = np.array([[5,7,3]])
perkalian = v1*v2
dot_product = v1.dot(v2.transpose())

print(perkalian, dot_product)

[[10 49 27]] [[86]]


In [ ]:
m1 = np.array([[2,7,9], [5,8,1]])
m2 = np.array([[4,1,6], [5,7,3]])
perkalian = m1*m2
dot_product = m1.dot(m2.transpose())

print(perkalian, dot_product)

[[ 8  7 54]
 [25 56  3]] [[69 86]
 [34 84]]


### Matrix Identitas dan Invers

#### Matrix Identitas

In [ ]:
#matrix identitas dengan n=3
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Determinan

In [ ]:
a = np.array([[0,1,0], [0,0,1], [4,-17,8]])
np.linalg.det(a)

4.0

#### Matrix Invers

In [4]:
m = np.array([[2,-1], [-1,1]])
m_inv = np.linalg.det(m)
m

array([[ 2, -1],
       [-1,  1]])

In [6]:
#manual
adj_m = np.array([[m[1][1], -1*m[0][1]], [-1*m[1][0], m[0][0]]])
det_m = np.linalg.det(m)
m_inv = (1/int(det_m) * adj_m)
m_inv

array([[1., 1.],
       [1., 2.]])

In [7]:
m.dot(m_inv)

array([[1., 0.],
       [0., 1.]])

### Solusi Sistem Persamaan

In [9]:
a = np.array([[1,1,2], [2,4,-3], [3,6,-5]])
b = np.array([9,1,0])
x = np.linalg.solve(a, b)
x

array([1., 2., 3.])

### Eigen

In [10]:
#nilai eigen
a = np.array([[0,0,-2], [1,2,1], [1,0,3]])
np.linalg.eigvals(a)

array([2., 1., 2.])

In [11]:
#vektor eigen
x = np.array([0,1,0])
a.dot(x) == 2*x

array([ True,  True,  True])